# This is a basic workflow to help you get started with Actions

name: simpleARMdeployment-01

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - uses: azure/Login@v2
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: 'Deploy ARM template'
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: '8d2220b0-923b-4e94-993f-d617b87aed27'
          resourceGroupName: 'rg-ghactions'
          template: './.arms/sa.json'
          parameters: |
            saName=distsa007x0002
          # Important: No Quotes around the parameter value!!!